export const LANGUAGES = [
  'assamese',
  'bengali',
  'bhili',
  'bodo',
  'dogri',
  'english',
  'garo',
  'gujarati',
  'gondi',
  'hindi',
  'ho',
  'kannada',
  'khandeshi',
  'kashmiri',
  'khasi',
  'konkani',
  'kurukh',
  'maithili',
  'malayalam',
  'marathi',
  'mundari',
  'meitei',
  'nepali',
  'odia',
  'punjabi',
  'sanskrit',
  'santali',
  'sindhi',
  'tamil',
  'telugu',
  'tulu',
  'urdu',
] as const;

export const LANGUAGE_OPTIONS = LANGUAGES.map((lang) => ({
  value: lang,
  label: lang.charAt(0).toUpperCase() + lang.slice(1),
}));
