#!/usr/bin/env sh
set -e


# Run formatting on staged files
npx lint-staged

# Check for untranslated i18n strings
npm run i18n:check

# Run tests with coverage
npm run test:coverage

# Run knip to check for unused files, dependencies, and exports
npm run knip

# Run type check and build
npm run build

# Run rollup build to ensure compatibility
npm run build:rd
